name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint_flask_sqlalchemy pylint_flask pytest
    - name: Install edgar_filing_searcher
      run: |
        cd python
        python setup.py install
        cd ..
    - name: Analysing the code with pylint
      run: |
        find . -type d \( -name build \) -prune -false -o -name *py | xargs pylint
